### ISSUE TITLE
Tags go out of the card

### ISSUE THREAD

**Issue by TheNinza** [ishandeveloper/Coursify-hacktoberfest#109]
**On resizing the tags go out of the card... This is resulting in tags to get hidden sometimes.**
![Screenshot from 2020-10-02 22-16-45](https://user-images.githubusercontent.com/62726436/94948746-74ef2a00-04fd-11eb-9c47-d7e01718d019.png)

**Comment by TheNinza** [comment]
assign me this

**Comment by ishandeveloper** [comment]
Hey @TheNinza . Thanks for taking out the time to create this issue. I've assigned this to you, please go ahead and create a PR.
### Goodluck! ✨

**Comment by TaneliR** [comment]
I could give this a try, if @TheNinza has abandoned it. 🤔

**Comment by TaneliR** [comment]
#126 Here's my PR for this issue.

**Comment by TheNinza** [comment]
I already submitted the pr
https://github.com/ishandeveloper/Coursify-hacktoberfest/pull/119

Thanks for ur concern @TaneliR
