### ISSUE TITLE
Add ability to filter the courses by tag names

### ISSUE THREAD

**Issue by ishandeveloper** [ishandeveloper/Coursify-hacktoberfest#32]
### Implement tag filters options,
so that the visitor can filter out the course results on the basis of technology/framework.

For the sake of this issue, you can assume having a few default filters (such as react, javascript, flutter, web etc), instead of scraping all the tags in the json data.

**Comment by LMulvey** [comment]
Hey, mind if I grab this issue?

**Comment by ishandeveloper** [comment]
Sure, Go ahead. I've assigned this to you 👍 

Goodluck! ✨
