### ISSUE TITLE
Add custom hero image to the courses

### ISSUE THREAD

**Issue by darshanr27** [ishandeveloper/Coursify-hacktoberfest#44]
Some of the courses missing the custom hero images. I can design custom images for some if you assign it to me.

**Comment by ishandeveloper** [comment]
Hey @darshanr27 . Thanks for taking out the time to create this issue. I've assigned this to you, please go ahead and create  a PR.

### Goodluck! ✨

**Comment by darshanr27** [comment]
👍,  Thank You @ishandeveloper

**Comment by darshanr27** [comment]
@ishandeveloper Do I need to continue creating a hero image for other courses?

**Comment by Om-Amitesh** [comment]
hey,
Is it alright for me to add a few hero images aswell?
