### ISSUE TITLE
Limit description by words instead of letters

### ISSUE THREAD

**Issue by TanishqSingla** [ishandeveloper/Coursify-hacktoberfest#65]
The description for the courses in the website is reduced by letters which is leading the words incomplete, this could lead several problems.
I would suggest in main.js at line 45
```js
${course.description.substring(1,100)}
```
this code be changed with something like this
```js
${course.description.split(" ").slice(1, 25).join(" ")}..
```

**Comment by ishandeveloper** [comment]
Hey @TanishqSingla , Thanks for taking out the time to create this issue.

I used that substring method, to limit the amount of text displayed in an individual card. With the proposed changes, there'd be several inconsistencies in the Card Size. 

Let's consider two examples, in first one, if the contributor is using words lenghty words like 'supercalifragilisticexpialidocious', or just forgot to add a space between two adjacent words, it'll be counted as just one word and that could lead to overflows in the text limit.

In second scenario, This proposed solution, might fail if the contributor adds adjectives or supportive words, as words such as 'for', 'of', 'and', 'or' will also be treated as a single word and that might would cause underflow of text in the card. 

Henceforth, I think this is a solution to a problem that does not exist yet. If you disagree with what I've said and would like to add something important, feel free to add a comment and reopen this issue, I'd love to discuss :) . But for now, I'm closing this issue. Thank you for your contribution.

### Happy Hacking! 🎊
