### ISSUE TITLE
Add Pagination Support [FEATURE]

### ISSUE THREAD

**Issue by ishandeveloper** [ishandeveloper/Coursify-hacktoberfest#73]
In the current implementation, all of the cards are shown in one single page, altogether.

Add Pagination support so that, a maximum of 12 Cards are shown on a page at a time. If visitor wants to view more courses, allow him/her to navigate to new pages.

For this issue, you can set the default maximum number of entries to 12 or anything else, instead of taking user's input about how many entries to show.

**Comment by iarmankhan** [comment]
Hey, I can work on this!

**Comment by ishandeveloper** [comment]
I've assigned this issue to you. Go ahead and make a PR.
### Goodluck! ✨

**Comment by iarmankhan** [comment]
Thank you! I'll complete this ASAP!

**Comment by ishandeveloper** [comment]
Closed by #79
