### ISSUE TITLE
It will be Cool if there is Back-To-Top button on the Page.

### ISSUE THREAD

**Issue by Bhargav252000** [ishandeveloper/Coursify-hacktoberfest#77]
I can add Back-To-Top button on the page mainly using JavaScript.

**Comment by Bhargav252000** [comment]
this PR fixes #78

**Comment by Bhargav252000** [comment]
> 
> 
> #78

**Comment by ishandeveloper** [comment]
Hey @Bhargav252000 ! 
Thanks for taking out the time to create this issue. This sounds cool! I've assigned this issue to you, please go ahead and make a PR.

### Goodluck! ✨

**Comment by ishandeveloper** [comment]
Closed by #78
